##
# address space homework files
#
# @file
# @version 0.1

memory_user: memory_user.o
	gcc -o memory_user memory_user.c -Wall -Werror
null: null.o
	gcc -o null null.c -Wall -Werror
clean:
	rm memory_user memory_user.o null null.o badmalloc badmalloc.o

# end
