##
# Project Title
#
# @file
# @version 0.1

q1: q1.o
	gcc -o q1 q1.c -Wall -Werror
q2: q2.o
	gcc -o q2 q2.c -Wall -Werror
q3: q3.o
	gcc -o q3 q3.c -Wall -Werror
q4: q4.o
	gcc -o q4 q4.c -Wall -Werror
q5: q5.o
	gcc -o q5 q5.c -Wall -Werror
q6: q6.o
	gcc -o q6 q6.c -Wall -Werror
q7: q7.o
	gcc -o q7 q7.c -Wall -Werror
clean:
	find . -maxdepth 1 -type f -name "q*" ! -name "*.c" -delete


# end
